//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyVThemeCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyVThemeCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string ANSWER_CANCEL {
            get {
                return ResourceManager.GetString("ANSWER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string ANSWER_NO {
            get {
                return ResourceManager.GetString("ANSWER_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string ANSWER_YES {
            get {
                return ResourceManager.GetString("ANSWER_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background colour.
        /// </summary>
        public static string BACKGROUND_COLOR {
            get {
                return ResourceManager.GetString("BACKGROUND_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CLEAR_BACKGROUND_IMAGE {
            get {
                return ResourceManager.GetString("CLEAR_BACKGROUND_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear background image.
        /// </summary>
        public static string CLEAR_BACKGROUND_IMAGE_TOOLTIP {
            get {
                return ResourceManager.GetString("CLEAR_BACKGROUND_IMAGE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string COLOR_PICKER_ADVANCED {
            get {
                return ResourceManager.GetString("COLOR_PICKER_ADVANCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Colours.
        /// </summary>
        public static string COLOR_PICKER_AVAILABLE_COLORS {
            get {
                return ResourceManager.GetString("COLOR_PICKER_AVAILABLE_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Colours.
        /// </summary>
        public static string COLOR_PICKER_RECENT_COLORS {
            get {
                return ResourceManager.GetString("COLOR_PICKER_RECENT_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string COLOR_PICKER_STANDARD {
            get {
                return ResourceManager.GetString("COLOR_PICKER_STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Colours.
        /// </summary>
        public static string COLOR_PICKER_STANDARD_COLORS {
            get {
                return ResourceManager.GetString("COLOR_PICKER_STANDARD_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create folder {0}.
        /// </summary>
        public static string CREATE_FOLDER_ERROR {
            get {
                return ResourceManager.GetString("CREATE_FOLDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally drop a background image here..
        /// </summary>
        public static string DROP_IMAGE {
            get {
                return ResourceManager.GetString("DROP_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-shadow blur radius.
        /// </summary>
        public static string DROP_SHADOW_BLUR_RADIUS {
            get {
                return ResourceManager.GetString("DROP_SHADOW_BLUR_RADIUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-shadow colour.
        /// </summary>
        public static string DROP_SHADOW_COLOR {
            get {
                return ResourceManager.GetString("DROP_SHADOW_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-shadow depth.
        /// </summary>
        public static string DROP_SHADOW_DEPTH {
            get {
                return ResourceManager.GetString("DROP_SHADOW_DEPTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-shadow opacity.
        /// </summary>
        public static string DROP_SHADOW_OPACITY {
            get {
                return ResourceManager.GetString("DROP_SHADOW_OPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string FONT_COLOR {
            get {
                return ResourceManager.GetString("FONT_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string FONT_OPACITY {
            get {
                return ResourceManager.GetString("FONT_OPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string FONT_SIZE {
            get {
                return ResourceManager.GetString("FONT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font style.
        /// </summary>
        public static string FONT_STYLE {
            get {
                return ResourceManager.GetString("FONT_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font weight.
        /// </summary>
        public static string FONT_WEIGHT {
            get {
                return ResourceManager.GetString("FONT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKGROUND.
        /// </summary>
        public static string HEADER_BACKGROUND {
            get {
                return ResourceManager.GetString("HEADER_BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BODY TEXT.
        /// </summary>
        public static string HEADER_BODY_TEXT {
            get {
                return ResourceManager.GetString("HEADER_BODY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE DIMENSIONS (pixels).
        /// </summary>
        public static string HEADER_IMAGE_DIMENSIONS {
            get {
                return ResourceManager.GetString("HEADER_IMAGE_DIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string HEADER_MISC {
            get {
                return ResourceManager.GetString("HEADER_MISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE TEXT.
        /// </summary>
        public static string HEADER_TITLE_TEXT {
            get {
                return ResourceManager.GetString("HEADER_TITLE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSE NUMBERS.
        /// </summary>
        public static string HEADER_VERSE_NOS {
            get {
                return ResourceManager.GetString("HEADER_VERSE_NOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal alignment.
        /// </summary>
        public static string HORZ_ALIGNMENT {
            get {
                return ResourceManager.GetString("HORZ_ALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom margin.
        /// </summary>
        public static string IMAGE_BOTTOM_MARGIN {
            get {
                return ResourceManager.GetString("IMAGE_BOTTOM_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string IMAGE_HEIGHT {
            get {
                return ResourceManager.GetString("IMAGE_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left margin.
        /// </summary>
        public static string IMAGE_LEFT_MARGIN {
            get {
                return ResourceManager.GetString("IMAGE_LEFT_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image opacity.
        /// </summary>
        public static string IMAGE_OPACITY {
            get {
                return ResourceManager.GetString("IMAGE_OPACITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right margin.
        /// </summary>
        public static string IMAGE_RIGHT_MARGIN {
            get {
                return ResourceManager.GetString("IMAGE_RIGHT_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top margin.
        /// </summary>
        public static string IMAGE_TOP_MARGIN {
            get {
                return ResourceManager.GetString("IMAGE_TOP_MARGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string IMAGE_WIDTH {
            get {
                return ResourceManager.GetString("IMAGE_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line spacing.
        /// </summary>
        public static string LINE_SPACING {
            get {
                return ResourceManager.GetString("LINE_SPACING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New theme.
        /// </summary>
        public static string NEW_THEME {
            get {
                return ResourceManager.GetString("NEW_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open theme.
        /// </summary>
        public static string OPEN_THEME {
            get {
                return ResourceManager.GetString("OPEN_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Theme.
        /// </summary>
        public static string OPEN_THEME_TITLE {
            get {
                return ResourceManager.GetString("OPEN_THEME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart Theme Creator after changing the language..
        /// </summary>
        public static string RESTART_LANGUAGE {
            get {
                return ResourceManager.GetString("RESTART_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample epub file.
        /// </summary>
        public static string SAMPLE_EPUB_FILE {
            get {
                return ResourceManager.GetString("SAMPLE_EPUB_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample text.
        /// </summary>
        public static string SAMPLE_TEXT {
            get {
                return ResourceManager.GetString("SAMPLE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save theme.
        /// </summary>
        public static string SAVE_THEME {
            get {
                return ResourceManager.GetString("SAVE_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save theme as....
        /// </summary>
        public static string SAVE_THEME_AS {
            get {
                return ResourceManager.GetString("SAVE_THEME_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Theme?.
        /// </summary>
        public static string SAVE_THEME_PROMPT_TITLE {
            get {
                return ResourceManager.GetString("SAVE_THEME_PROMPT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Theme.
        /// </summary>
        public static string SAVE_THEME_TITLE {
            get {
                return ResourceManager.GetString("SAVE_THEME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string SHOW_VERSE_NOS {
            get {
                return ResourceManager.GetString("SHOW_VERSE_NOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme file.
        /// </summary>
        public static string THEME_FILE {
            get {
                return ResourceManager.GetString("THEME_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string TITLE_POSITION {
            get {
                return ResourceManager.GetString("TITLE_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle background image.
        /// </summary>
        public static string TOGGLE_IMAGE {
            get {
                return ResourceManager.GetString("TOGGLE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle background.
        /// </summary>
        public static string TOGGLE_IMAGE_TOOLTIP {
            get {
                return ResourceManager.GetString("TOGGLE_IMAGE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use drop-shadow.
        /// </summary>
        public static string USE_DROP_SHADOW {
            get {
                return ResourceManager.GetString("USE_DROP_SHADOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical alignment.
        /// </summary>
        public static string VERT_ALIGNMENT {
            get {
                return ResourceManager.GetString("VERT_ALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme has changed. Do you want to save?.
        /// </summary>
        public static string WANT_TO_SAVE {
            get {
                return ResourceManager.GetString("WANT_TO_SAVE", resourceCulture);
            }
        }
    }
}
