//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use abbreviated book names.
        /// </summary>
        public static string ABBREVIATED_BOOK_NAME {
            get {
                return ResourceManager.GetString("ABBREVIATED_BOOK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added file.
        /// </summary>
        public static string ADDED_FILE {
            get {
                return ResourceManager.GetString("ADDED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} files.
        /// </summary>
        public static string ADDED_X_FILES {
            get {
                return ResourceManager.GetString("ADDED_X_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow verse editing.
        /// </summary>
        public static string ALLOW_VERSE_EDITING {
            get {
                return ResourceManager.GetString("ALLOW_VERSE_EDITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window always on top.
        /// </summary>
        public static string ALWAYS_ON_TOP {
            get {
                return ResourceManager.GetString("ALWAYS_ON_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlyV software version: {0}.
        /// </summary>
        public static string APP_VER {
            get {
                return ResourceManager.GetString("APP_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto fit.
        /// </summary>
        public static string AUTO_FIT {
            get {
                return ResourceManager.GetString("AUTO_FIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible epub file.
        /// </summary>
        public static string BIBLE_EPUB_FILE {
            get {
                return ResourceManager.GetString("BIBLE_EPUB_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Blue {
            get {
                object obj = ResourceManager.GetObject("Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK.
        /// </summary>
        public static string BOOK {
            get {
                return ResourceManager.GetString("BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER.
        /// </summary>
        public static string CHAPTER {
            get {
                return ResourceManager.GetString("CHAPTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        public static string COPIED {
            get {
                return ResourceManager.GetString("COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy image to clipboard.
        /// </summary>
        public static string COPY_TO_CLIPBOARD {
            get {
                return ResourceManager.GetString("COPY_TO_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read one of the files!.
        /// </summary>
        public static string COULD_NOT_READ_1 {
            get {
                return ResourceManager.GetString("COULD_NOT_READ_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read any of the files!.
        /// </summary>
        public static string COULD_NOT_READ_ANY {
            get {
                return ResourceManager.GetString("COULD_NOT_READ_ANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file!.
        /// </summary>
        public static string COULD_NOT_READ_FILE {
            get {
                return ResourceManager.GetString("COULD_NOT_READ_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read {0} files!.
        /// </summary>
        public static string COULD_NOT_READ_X {
            get {
                return ResourceManager.GetString("COULD_NOT_READ_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create folder {0}.
        /// </summary>
        public static string CREATE_FOLDER_ERROR {
            get {
                return ResourceManager.GetString("CREATE_FOLDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DEFAULT_THEME {
            get {
                return ResourceManager.GetString("DEFAULT_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Folder.
        /// </summary>
        public static string DEST_FOLDER {
            get {
                return ResourceManager.GetString("DEST_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display (F5).
        /// </summary>
        public static string DISPLAY_CMD {
            get {
                return ResourceManager.GetString("DISPLAY_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop into OnlyM to create a slideshow.
        /// </summary>
        public static string DRAG_INTO_ONLYM {
            get {
                return ResourceManager.GetString("DRAG_INTO_ONLYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Bible epub files from jw.org and drag and drop here..
        /// </summary>
        public static string DROP_BIBLE_INSTRUCTIONS {
            get {
                return ResourceManager.GetString("DROP_BIBLE_INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This editor is typically used to abbreviate verses (e.g. to replace a sentence with an ellipsis). Your modifications are remembered until you close OnlyV..
        /// </summary>
        public static string EDIT_INSTRUCTIONS {
            get {
                return ResourceManager.GetString("EDIT_INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ellipses for continuation.
        /// </summary>
        public static string ELLIPSIS_CONTINUATION {
            get {
                return ResourceManager.GetString("ELLIPSIS_CONTINUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible epub not found!.
        /// </summary>
        public static string EPUB_NOT_FOUND {
            get {
                return ResourceManager.GetString("EPUB_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible epub not specified!.
        /// </summary>
        public static string EPUB_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("EPUB_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving images!.
        /// </summary>
        public static string ERROR_SAVING {
            get {
                return ResourceManager.GetString("ERROR_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, download a Bible epub file from jw.org and then drag and drop it here..
        /// </summary>
        public static string GET_STARTED_INSTRUCTIONS {
            get {
                return ResourceManager.GetString("GET_STARTED_INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIBLES.
        /// </summary>
        public static string HEADER_BIBLES {
            get {
                return ResourceManager.GetString("HEADER_BIBLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPLAY.
        /// </summary>
        public static string HEADER_DISPLAY {
            get {
                return ResourceManager.GetString("HEADER_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE STYLE.
        /// </summary>
        public static string HEADER_IMAGE_STYLE {
            get {
                return ResourceManager.GetString("HEADER_IMAGE_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISCELLANEOUS.
        /// </summary>
        public static string HEADER_MISC {
            get {
                return ResourceManager.GetString("HEADER_MISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide (F5).
        /// </summary>
        public static string HIDE_CMD {
            get {
                return ResourceManager.GetString("HIDE_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images folder.
        /// </summary>
        public static string IMAGES_FOLDER {
            get {
                return ResourceManager.GetString("IMAGES_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert closing quotation mark.
        /// </summary>
        public static string INSERT_CLOSING_QUOTE {
            get {
                return ResourceManager.GetString("INSERT_CLOSING_QUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert opening quotation mark.
        /// </summary>
        public static string INSERT_OPENING_QUOTE {
            get {
                return ResourceManager.GetString("INSERT_OPENING_QUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JW Library compatibility mode.
        /// </summary>
        public static string JW_COMPAT_MODE {
            get {
                return ResourceManager.GetString("JW_COMPAT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;JW Library&quot; is a registered trademark of Watch Tower Bible and Tract Society of Pennsylvania.
        /// </summary>
        public static string JWL_TRADEMARK {
            get {
                return ResourceManager.GetString("JWL_TRADEMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string LOG_LEVEL_DEBUG {
            get {
                return ResourceManager.GetString("LOG_LEVEL_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LOG_LEVEL_ERROR {
            get {
                return ResourceManager.GetString("LOG_LEVEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string LOG_LEVEL_FATAL {
            get {
                return ResourceManager.GetString("LOG_LEVEL_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string LOG_LEVEL_INFORMATION {
            get {
                return ResourceManager.GetString("LOG_LEVEL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string LOG_LEVEL_VERBOSE {
            get {
                return ResourceManager.GetString("LOG_LEVEL_VERBOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LOG_LEVEL_WARNING {
            get {
                return ResourceManager.GetString("LOG_LEVEL_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging level.
        /// </summary>
        public static string LOGGING_LEVEL {
            get {
                return ResourceManager.GetString("LOGGING_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media monitor.
        /// </summary>
        public static string MEDIA_MONITOR {
            get {
                return ResourceManager.GetString("MEDIA_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MONITOR_NONE {
            get {
                return ResourceManager.GetString("MONITOR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available!.
        /// </summary>
        public static string NEW_UPDATE_AVAILABLE {
            get {
                return ResourceManager.GetString("NEW_UPDATE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next image.
        /// </summary>
        public static string NEXT_IMAGE {
            get {
                return ResourceManager.GetString("NEXT_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preview page.
        /// </summary>
        public static string NEXT_PAGE_PREVIEW {
            get {
                return ResourceManager.GetString("NEXT_PAGE_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images to save!.
        /// </summary>
        public static string NO_IMAGES {
            get {
                return ResourceManager.GetString("NO_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlyV cannot write to the &apos;{0}&apos; folder.
        /// </summary>
        public static string NO_WRITE_ACCESS {
            get {
                return ResourceManager.GetString("NO_WRITE_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 image generated.
        /// </summary>
        public static string ONE_IMAGE_GENERATED {
            get {
                return ResourceManager.GetString("ONE_IMAGE_GENERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous image.
        /// </summary>
        public static string PREV_IMAGE {
            get {
                return ResourceManager.GetString("PREV_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show scriptures page.
        /// </summary>
        public static string PREV_PAGE_SCRIPS {
            get {
                return ResourceManager.GetString("PREV_PAGE_SCRIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible reader not initialised!.
        /// </summary>
        public static string READER_NOT_INIT {
            get {
                return ResourceManager.GetString("READER_NOT_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the verse text.
        /// </summary>
        public static string RESET_VERSE_TEXT {
            get {
                return ResourceManager.GetString("RESET_VERSE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart OnlyV after changing the language..
        /// </summary>
        public static string RESTART_LANGUAGE {
            get {
                return ResourceManager.GetString("RESTART_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to images folder.
        /// </summary>
        public static string SAVE_TO_IMAGES {
            get {
                return ResourceManager.GetString("SAVE_TO_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved image.
        /// </summary>
        public static string SAVED_IMAGE {
            get {
                return ResourceManager.GetString("SAVED_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved {0} images.
        /// </summary>
        public static string SAVED_X_IMAGES {
            get {
                return ResourceManager.GetString("SAVED_X_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Destination Folder.
        /// </summary>
        public static string SELECT_FOLDER {
            get {
                return ResourceManager.GetString("SELECT_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings disabled by administrator!.
        /// </summary>
        public static string SETTINGS_DISABLED {
            get {
                return ResourceManager.GetString("SETTINGS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page.
        /// </summary>
        public static string SETTINGS_PAGE {
            get {
                return ResourceManager.GetString("SETTINGS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show verse numbers.
        /// </summary>
        public static string SHOW_VERSE_NOS {
            get {
                return ResourceManager.GetString("SHOW_VERSE_NOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text scaling.
        /// </summary>
        public static string TEXT_SCALING {
            get {
                return ResourceManager.GetString("TEXT_SCALING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space between title verse numbers.
        /// </summary>
        public static string TITLE_VERSE_NOS {
            get {
                return ResourceManager.GetString("TITLE_VERSE_NOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim punctuation.
        /// </summary>
        public static string TRIM_PUNCTUATION {
            get {
                return ResourceManager.GetString("TRIM_PUNCTUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim quotation marks.
        /// </summary>
        public static string TRIM_QUOTES {
            get {
                return ResourceManager.GetString("TRIM_QUOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use background image.
        /// </summary>
        public static string USE_BACKGROUND_IMAGE {
            get {
                return ResourceManager.GetString("USE_BACKGROUND_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ellipses to indicate non-contiguous verses.
        /// </summary>
        public static string USE_ELLIPSES {
            get {
                return ResourceManager.GetString("USE_ELLIPSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a tilde between paragraphs in a single verse.
        /// </summary>
        public static string USE_TILDE {
            get {
                return ResourceManager.GetString("USE_TILDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSES.
        /// </summary>
        public static string VERSES {
            get {
                return ResourceManager.GetString("VERSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        public static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} images generated..
        /// </summary>
        public static string X_IMAGES_GENERATED {
            get {
                return ResourceManager.GetString("X_IMAGES_GENERATED", resourceCulture);
            }
        }
    }
}
