//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlyV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlyV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added file.
        /// </summary>
        internal static string ADDED_FILE {
            get {
                return ResourceManager.GetString("ADDED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} files.
        /// </summary>
        internal static string ADDED_X_FILES {
            get {
                return ResourceManager.GetString("ADDED_X_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        internal static string COPIED {
            get {
                return ResourceManager.GetString("COPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read one of the files!.
        /// </summary>
        internal static string COULD_NOT_READ_1 {
            get {
                return ResourceManager.GetString("COULD_NOT_READ_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read any of the files!.
        /// </summary>
        internal static string COULD_NOT_READ_ANY {
            get {
                return ResourceManager.GetString("COULD_NOT_READ_ANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read file!.
        /// </summary>
        internal static string COULD_NOT_READ_FILE {
            get {
                return ResourceManager.GetString("COULD_NOT_READ_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read {0} files!.
        /// </summary>
        internal static string COULD_NOT_READ_X {
            get {
                return ResourceManager.GetString("COULD_NOT_READ_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create folder {0}.
        /// </summary>
        internal static string CREATE_FOLDER_ERROR {
            get {
                return ResourceManager.GetString("CREATE_FOLDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Folder.
        /// </summary>
        internal static string DEST_FOLDER {
            get {
                return ResourceManager.GetString("DEST_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display (F5).
        /// </summary>
        internal static string DISPLAY_CMD {
            get {
                return ResourceManager.GetString("DISPLAY_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible epub not found!.
        /// </summary>
        internal static string EPUB_NOT_FOUND {
            get {
                return ResourceManager.GetString("EPUB_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible epub not specified!.
        /// </summary>
        internal static string EPUB_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("EPUB_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving images!.
        /// </summary>
        internal static string ERROR_SAVING {
            get {
                return ResourceManager.GetString("ERROR_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide (F5).
        /// </summary>
        internal static string HIDE_CMD {
            get {
                return ResourceManager.GetString("HIDE_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string MONITOR_NONE {
            get {
                return ResourceManager.GetString("MONITOR_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preview page.
        /// </summary>
        internal static string NEXT_PAGE_PREVIEW {
            get {
                return ResourceManager.GetString("NEXT_PAGE_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images to save!.
        /// </summary>
        internal static string NO_IMAGES {
            get {
                return ResourceManager.GetString("NO_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show scriptures page.
        /// </summary>
        internal static string PREV_PAGE_SCRIPS {
            get {
                return ResourceManager.GetString("PREV_PAGE_SCRIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible reader not initialised!.
        /// </summary>
        internal static string READER_NOT_INIT {
            get {
                return ResourceManager.GetString("READER_NOT_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved image.
        /// </summary>
        internal static string SAVED_IMAGE {
            get {
                return ResourceManager.GetString("SAVED_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved {0} images.
        /// </summary>
        internal static string SAVED_X_IMAGES {
            get {
                return ResourceManager.GetString("SAVED_X_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page.
        /// </summary>
        internal static string SETTINGS_PAGE {
            get {
                return ResourceManager.GetString("SETTINGS_PAGE", resourceCulture);
            }
        }
    }
}
